services:
  postgres_db:
    image: postgres:15-alpine
    container_name: notes_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - notes_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  notes_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=postgres_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - PORT=${PORT}
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - notes_network

volumes:
  pgdata:

networks:
  notes_network:
    driver: bridge